NHSDigital/dtos-communication-management

- .env.example
- compose.yml
- dependencies/azurite/Dockerfile
- dependencies/azurite/azurite-setup.py
Adds compose.yml which starts both azure functions along with Azurite. 
Azurite is configured with the blob container 'pilot-data'.
Docker compose is used to build artefacts for our deployment pipelines.
---
> Add a barebones docker compose recipe

- docs/developer-guides/Local_development_setup.md
Documents the more simplified method of running functions with docker compose.
We've updated the project with a docker compose recipe for running functions and storage emulation.
---
> Update developer docs

- src/functions/process_pilot_data/data_processor.py
- tests/process_pilot_data/test_data_processor.py
This doesn't currently look up the correct routing plan id for sandbox on the notify function side of things. 
We may have missed this because e2e tests are not currently being run on CI.
```python
ROUTING_PLANS.get(key)[os.getenv("ENV") or "sandbox"]
```
returns `None` [because the key is `breast-screening-pilot`](https://github.com/NHSDigital/dtos-communication-management/blob/main/src/functions/notify/routing_plans.py#L12)
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will …
> We should currently send 'breast-screening-pilot' as the `routing_plan` payload value

- .azuredevops/pipelines/cd-infrastructure-dev-audit.yaml
- .azuredevops/pipelines/cd-infrastructure-dev-core.yaml
- .github/actions/lint-terraform/action.yaml
- compose.yml
- infrastructure/.gitignore
- infrastructure/tf-audit/app_insights.tf
- infrastructure/tf-audit/config.tf
- infrastructure/tf-audit/data.tf
- infrastructure/tf-audit/environments/development.tfvars
- infrastructure/tf-audit/log_analytics_workspace.tf
- infrastructure/tf-audit/networking.tf
- infrastructure/tf-audit/private_link_scopes.tf
- infrastructure/tf-audit/provider.tf
- infrastructure/tf-audit/variables.tf
- infrastructure/tf-core/app_service_plan.tf
- infrastructure/tf-core/config.tf
- infrastructure/tf-core/data.tf
- infrastructure/tf-core/environments/development.tfvars
- infrastructure/tf-core/function_app.tf
- infrastructure/tf-core/key_vault.tf
- infrastructure/tf-core/network_routing.tf
- infrastructure/tf-core/networking.tf
- infrastructure/tf-core/provider.tf
- infrastructure/tf-core/rbac.tf
- infrastructure/tf-core/storage.tf
- infrastructure/tf-core/variables.tf
- scripts/terraform/terraform.mk
Initial infrastructure build:
- Project-specific Azure Container Registry deployed to Hub subscription.
- Continuous Integration pipeline working, changes to functions will build on commit, will upload to ACR on merge to main.
- Continuous Deployment pipelines for Development environment.
- Audit infrastructure deployed to Audit subscription (App Insights, Log Analytics Workspace, networking, peering to Hub subscription networking, Private Link).
- Core infrastructure deployed to Core Services subscription (Function Apps, Key Vault, networking, peering to Hub subscription, routing)
Audit infra deployment result:
https://dev.azure.com/nhse-dtos/dtos-communication-management/_build/results?buildId=4906&view=results
Core infra deployment result: …
> feat: DTOSS-4810 Initial infrastructure build

- .env.e2e
- .env.example
- compose.yml
- src/functions/status_callback/Dockerfile
- src/functions/status_callback/function_app.py
- src/functions/status_callback/request_verifier.py
- tests/status_callback/test_function_app.py
- tests/status_callback/test_request_verifier.py
Adds a request verifier which examines a specific header for a specific HMAC encoded signature. The content of the encoded signature is the request body hashed with a secret.
Any requests which are missing one of the two headers used to verify the signature will return a 401 response.
Any requests which don't have a matching signature header will return a 403 response.
The callback function will receive message status updates from NHS Notify. Requests to the function should be verified as per the [NHS Notify documentation](https://digital.nhs.uk/developer/api-catalogue/nhs-notify#overview--receive-a-callback)
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable …
> Add HMAC signature verifier to callback function

- src/functions/message_status/function_app.py
- tests/message_status/test_function_app.py
Changes message status function path to something more appropriate.
We don't need to specify the intended use of the function in the path name.
---
> Amend path for message status function

- Pipfile
- Pipfile.lock
- compose.yml
- src/functions/notify/Dockerfile
- test-pacts.sh
- test-unit.sh
- test.sh
- tests/conftest.py
- tests/end_to_end/Dockerfile
- Fixes missing container configuration.
- Clears end to end test container logs before running tests.
- Re-enables end to end tests
- Re-enables pact tests with PendingDeprecationWarnings suppressed.
- Prints unit test descriptions to test ouput
A couple of issues with end to end tests cropped up due to missing dependencies in recent merges.
These were valid test failures due to missing container configurations.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR …
> Fix end to end tests

- src/functions/notify/batch_message_recorder.py
- src/functions/notify/notifier.py
- src/shared/uuid_generator.py
- tests/unit/notify/test_batch_message_recorder.py
- tests/unit/notify/test_notifier.py
- tests/unit/shared/__init__.py
- tests/unit/shared/test_uuid_generator.py
Extracts uuid generation and record saving from the `notifier` module.
Adds unit tests for extracted functions.
Our `notifier` module has too many responsibilities and is proving harder to test reliably.
---
> Refactor notifier saving batch messages

- src/functions/notify/notifier.py
We won't be exposing any secrets in logs, but this commit provides us with a way to prove that the Azure KeyVault to environment variable resolution is working properly.
---
> Add a disposable proof that we can configure and access a keyvault secret via the Azure function app environment

- src/functions/process_pilot_data/pilot_bso_details.py
- tests/unit/process_pilot_data/test_pilot_bso_details.py
Allow any case BSO code in CSV file name
We received a file from a BSO with the code in lowercase. We've assumed uppercase. It shouldn't matter.
---
> Allow lowercase bso code prefixes

- .azuredevops/pipelines/cd-infrastructure-pre-audit.yaml
- .azuredevops/pipelines/cd-infrastructure-pre-core.yaml
- infrastructure/tf-audit/environments/preprod.tfvars
- infrastructure/tf-core/environments/preprod.tfvars
Create preprod environment and pipelines.
Successfully deployed:
- preprod audit state: https://dev.azure.com/nhse-dtos/dtos-communication-management/_build/results?buildId=9408&view=results
- preprod core state: https://dev.azure.com/nhse-dtos/dtos-communication-management/_build/results?buildId=9431&view=results
---
> feat: add preprod deployment

- .azuredevops/pipelines/acr-image-retag.yaml
This adds a new ADO pipeline here:
https://dev.azure.com/nhse-dtos/dtos-communication-management/_build?view=folders
Successful run here:
https://dev.azure.com/nhse-dtos/dtos-communication-management/_build/results?buildId=9642&view=results
Docker containers built by the CI process are uploaded to the ACR tagged with `development`.
The new **ACR images re-tag** pipeline created by this PR allows the latest versions of those images to be targeted, and to be re-tagged with either `nft` or `integration`. Once that is done, the Function Apps in those respective environments will pull the latest image with the matching tags when they are restarted.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable …
> feat: add ACR image re-tagging pipeline for non-live

- infrastructure/tf-core/environments/development.tfvars
- infrastructure/tf-core/environments/integration.tfvars
- infrastructure/tf-core/environments/nft.tfvars
- infrastructure/tf-core/environments/preprod.tfvars
Advice from @patrickmoore-nc was to downgrade the db spec.
---
> Downgrade database to 2 vCPU, 8 GB RAM

- infrastructure/tf-core/environments/integration.tfvars
- infrastructure/tf-core/environments/nft.tfvars
These were copied from a [different PR](https://github.com/NHSDigital/dtos-communication-management/pull/78) but the dev values were replicated across all envs. My bad. Use int and nft values where applicable.
See https://github.com/NHSDigital/dtos-communication-management/pull/78/files#diff-416014777a037a6c459f68e076ef6249c593dce4283a209230ecc48ed963ededR183 and https://github.com/NHSDigital/dtos-communication-management/pull/78/files#diff-9707955a3b50407bb69f3d54db7e045ebcef4c3e264000caced87d7a20004d68R184 which appears to use int for nft and vice versa, I've assumed this should be the other way around in the changes here.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID …
> Fix database host and user values for int and nft

- src/functions/message_status/function_app.py
- src/functions/notify/function_app.py
- src/functions/process_pilot_data/function_app.py
- tests/unit/message_status/test_function_app.py
Adds initialisation logging for each function for consistency, this gives us a trigger timestamp in our logs for each function trigger.
---
> Add logging for initialization of each function

- src/shared/datastore.py
Reverts NHSDigital/dtos-communication-management#98
> Revert "Trigger pipeline"

- compose.yml
- database/schema.sql
- src/shared/datastore.py
- tests/end_to_end/Dockerfile
- tests/integration/Dockerfile
- Check for initialised schema on connection.
- Initialise db schema on connection if not present.
- Regret having to do this in the application codebase and accept it as tech-debt.
No tests added as we have removed auto initialisation from docker compose, so all integration and end to end tests would fail if the schema isn't being initialised as expected.
We are not yet able to implement the Azure / Postgres deployment example of how to initialise a database schema. So we need to fall back to implementing in the application codebase. 
Yes, I'm unhappy too.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable …
> Initialise database

- src/shared/datastore.py
- tests/end_to_end/Dockerfile
- tests/integration/Dockerfile
Amend the file path in favour of deployed environment rather than test containers.
This did not resolve as expected when deployed.
---
> Adjust path to schema file

- src/functions/message_status/Dockerfile
- src/functions/notify/Dockerfile
Add missing `COPY` statement to move schema to function app codebase.
We will be initialising the schema in the function application runtime (temporarily) so make sure the schema SQL file is copied across into the function app containers.
---
> Copy schema to function app source

- scripts/config/gitleaks.toml
- src/functions/notify/notifier.py
- tests/unit/notify/test_notifier.py
Reverts NHSDigital/dtos-communication-management#84
> Revert "contact_telephone_number > phoneNumber in request to Notify"

- Pipfile
- Pipfile.lock
- src/shared/datastore.py
- tests/unit/shared/test_datastore.py
- Remove MI token retrieval code, this failed to give us a usable connection and should be done prior to any attempt to obtain a connection.
- Add a test around schema initialisation, ensure it only happens once.
---
> Remove mi access token retrieval

- infrastructure/tf-core/environments/development.tfvars
- infrastructure/tf-core/environments/integration.tfvars
- infrastructure/tf-core/environments/nft.tfvars
- infrastructure/tf-core/environments/preprod.tfvars
- infrastructure/tf-core/environments/production.tfvars
- infrastructure/tf-core/function_app.tf
- infrastructure/tf-core/variables.tf
Fix the `AzureWebJobsStorage__accountName` env var as this wasn't quite right.
Remove incorrectly named storage uri vars. 
The blobServiceUri and queueServiceUri vars names were not correct and don't seem to have any effect on uploading to storage anyway. 
See https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings for var names.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really …
> Amend AzureWebJobsStorage env vars

- src/functions/message_status/function_app.py
This will help us with HMAC signature verification from NHS Notify callbacks.
---
> Log headers we use to verify requests

- src/functions/process_pilot_data/data_processor.py
- tests/unit/process_pilot_data/__init__.py
Remove data mutation in function which returns a valid row. This allows us to implicitly drop data we don't want to send on to the Notify function.
---
> Remove data mutation from data processor

- src/functions/notify/batch_message_recorder.py
- src/functions/notify/notifier.py
- src/shared/uuid_generator.py
- tests/integration/test_notifier_saves_batch_message_status_records.py
- tests/pacts/notifyazurefunction-nhsnotify.json
- tests/pacts/test_nhs_notify_create_message.py
- tests/unit/notify/test_batch_message_recorder.py
- tests/unit/notify/test_notifier.py
- tests/unit/shared/test_uuid_generator.py
- Make `messageReference` a unique value
- Make `recipientId` a hash of recipient details and appointment details
We based the `messageReference` value we send to notify on the recipient and appointment data, meaning it was not unique.  This is no longer necessary with the way we record data in the database, we can now use a unique reference per recipient per NHS Notify request and this gets saved in the db consistently.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove …
> Make `messageReference` unique

- src/functions/notify/routing_plans.py
- Rename `sandbox` routing plan entry key to `development`
- Add `nft` routing plan entry, this contains the same value as `integration`
We have an env var which we depend on to look up the appropriate set of routing plans.
The values are `DEVELOPMENT`, `NFT` and `INTEGRATION` and we will be adding a production one soon.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate your cooperation in this …
> Add routing plan entries for all current environments

- src/functions/notify/routing_plans.py
Add production NHS Notify routing plan ID for BS Pilot
We now have several duplicate entries and will revisit how we structure these, but this is currently what is needed to run the pilot in production.
---
> Add production routing plan ID

- src/functions/message_status/function_app.py
- src/functions/notify/notifier.py
- src/functions/process_pilot_data/data_processor.py
- src/functions/process_pilot_data/function_app.py
- src/shared/datastore.py
- tests/unit/message_status/test_function_app.py
We can reduce some of the noise in the logs now we have run a handful of high-volume tests.
---
> Reduce levels for some of the diagnostic log statements

- .azuredevops/pipelines/cd-infrastructure-dev-audit.yaml
- .azuredevops/pipelines/cd-infrastructure-dev-core.yaml
- .azuredevops/pipelines/cd-infrastructure-int-audit.yaml
- .azuredevops/pipelines/cd-infrastructure-int-core.yaml
- .azuredevops/pipelines/cd-infrastructure-nft-audit.yaml
- .azuredevops/pipelines/cd-infrastructure-nft-core.yaml
- .azuredevops/pipelines/cd-infrastructure-prd-audit.yaml
- .azuredevops/pipelines/cd-infrastructure-prd-core.yaml
- .azuredevops/pipelines/cd-infrastructure-pre-audit.yaml
- .azuredevops/pipelines/cd-infrastructure-pre-core.yaml
- infrastructure/tf-core/diagnostic_settings.tf
- infrastructure/tf-core/function_app.tf
- infrastructure/tf-core/locals.tf
- infrastructure/tf-core/postgresql.tf
> feat: DTOS 00000 adding config for postgresql ds

- src/notify/app/route_handlers/message.py
- src/notify/app/routes.py
- src/notify/app/services/datastore.py
- src/notify/app/services/message_batch_dispatcher.py
- src/notify/app/services/message_batch_recorder.py
- src/notify/app/utils/access_token.py
- src/notify/app/utils/database.py
- src/notify/app/utils/uuid_generator.py
- src/notify/app/validators/request_validator.py
- src/notify/app/validators/schema_validator.py
- tests/conftest.py
- tests/integration/notify/app/route_handlers/test_message_batch.py
- tests/integration/notify/app/route_handlers/test_status_create_endpoint.py
- tests/unit/notify/app/services/test_datastore.py
- tests/unit/notify/app/services/test_message_batch_dispatcher.py
- tests/unit/notify/app/services/test_message_batch_recorder.py
- tests/unit/notify/app/utils/test_access_token.py
- tests/unit/notify/app/utils/test_uuid_generator.py
- Add `POST /api/message/create` endpoint which expects the same request body as NHS Notify's `MessageBatch` endpoint.
- Forwards post data in request to NHS Notify's `POST /v1/message-batches` endpoint.
- Validate request body using NHS Notify OAS schema for `MessageBatch`
- Persist the message batch for both `sent` and `failed` response states from NHS Notify
- Persist individual message per recipient with relevant message ID and reference UUID
- Respond with NHS Notify status code
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in …
> Add message batch endpoint

- docs/developer-guides/Local_development_setup.md
Update docs describing local development environment and local test environment setup.
How we run local developer environments and tests is changing so that Docker is no longer a prerequisite.
---
> Update developer documentation

- compose.yml
- src/notify/Dockerfile
- src/notify/file_processor/csv_file_processor.py
- src/notify/file_processor/format_date.py
- src/notify/file_processor/format_time.py
- src/notify/file_processor/office_details.py
- src/notify/function_app.py
- src/notify/local.settings.json
- tests/conftest.py
- tests/unit/notify/file_processor/test_csv_file_processor.py
- tests/unit/notify/file_processor/test_format_date.py
- tests/unit/notify/file_processor/test_format_time.py
- tests/unit/notify/file_processor/test_office_details.py
- tests/unit/notify/test_function_app.py
- Adds the same blob trigger function from the BSO Pilot into the function app which contains the flask app. This reduces the overhead in maintaining and deploying multiple function apps and all the boilerplate and module import headaches caused by Azure V2 function apps.
- Uses the same expectations about CSV data, the routing plan can/should be derived from the filename. There's likely more work to be done here around how we register routing plans, not in scope for this PR.
- Calls the same message batch dispatcher as the API endpoint.
- Validates the message batch POST body generated from the CSV data against the NHS Notify OAS schema.
We don't want to lose the functionality from the BSO Pilot (i.e. CSV uploads calling Notify) but we now do this via the NHS Notify message batch …
> Add CSV file processor to function app

- .github/workflows/stage-2-test.yaml
- .pylintrc.toml
- Pipfile
- Pipfile.lock
- src/notify/app/models.py
- src/notify/app/route_handlers/message.py
- src/notify/app/route_handlers/status.py
- src/notify/app/services/message_batch_dispatcher.py
- src/notify/app/services/message_batch_recorder.py
- src/notify/app/services/status_recorder.py
- src/notify/app/services/status_reporter.py
- src/notify/app/utils/access_token.py
- src/notify/app/utils/database.py
- src/notify/app/validators/schema_validator.py
- src/notify/file_processor/csv_file_processor.py
- src/notify/file_processor/format_time.py
- src/notify/file_processor/office_details.py
- src/notify/function_app.py
Lint applicable code with pylint. Uses some sensible overrides/exceptions.
We should lint our code. So far style has been consistent because we've only had a couple of contributors.
---
> Add pylint

- src/notify/file_processor/csv_file_processor.py
- tests/conftest.py
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-7848
We were receiving 400 errors with no error detail from NHS Notify API.
The lack of error detail is an issue on their end but the underlying cause was supplying an ODS code.
Removing this means we make successful requests.
@dnimmo https://github.com/NHSDigital/dtos-communication-management/pull/197 is affected by this, I tested using the `T8T9T` code and got a 400 response with no error explanation, consistent with the bug we are seeing.
Removing the code altogether for now.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-th …
> Omit the ODS code, we are not set up for ODS override
