NHSDigital/dtos-communication-management

- .env.example
- .gitignore
- compose.yml
- src/functions/notify/Dockerfile
- src/functions/notify/__init__.py
- src/functions/notify/function_app.py
- src/functions/notify/helper.py
- src/functions/notify/local.settings.json
- src/functions/notify/requirements.txt
- src/functions/notify/tests/test_function_app.py
- src/functions/notify/tests/test_helper.py
- src/functions/process_pilot_data/__init__.py
- src/functions/process_pilot_data/function_app.py
- src/functions/process_pilot_data/requirements.txt
- src/functions/process_pilot_data/tests/test_function_app.py
- src/functions/process_pilot_data/tests/test_helper.py
- Disables access token lookup for development purposes - we can't access any non-sandbox Notify API endpoints without necessary secrets.
- Adds tests for access token lookup - this code had little coverage.
- Refactors a bunch of environment variables - more descriptive names and more env vars to help configure things.
- Configure docker compose with values from environment
- Refactors module names to use function name as top level module.
This PR addresses a few things but the main intention is to make `docker compose up` and the full test suite work locally while we await Notify API integration details.
Access token lookup is not currently working because we don't have full Notify API integration yet so we are missing an API key and some other information. The test suite has some …
> Refactor access token, env vars, module names

- tests/test_end_to_end.py
Uses `pytest.skip` in a setup fixture if `GITHUB_ACTIONS` env var is not present when running the test or test suite.
---
> Use `pytest.skip` to skip end to end test

- compose.yml
- src/functions/notify/host.json
- src/functions/process_pilot_data/host.json
- test-end-to-end.sh
- test.sh
- tests/end_to_end/Dockerfile
- tests/end_to_end/test_file_upload_to_notifying_recipients.py
Adds a bespoke end to end test container which depends on the successful completion of azurite setup. This means the azurite blob containers are present and writable. The e2e test container shares logs with the function apps which allows it to poll for expected log output indicating the functions have been triggered and the execution was successful.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate …
> Run end to end tests in their own container

- src/functions/notify/host.json
- src/functions/process_pilot_data/host.json
We don't need trace level logging for functions and peripheral runtime information so reduce logging levels. We might review this in future but keep the noise down to info from functions and warnings from elsewhere.
I think end to end tests are affected by overt logging verbosity. In a production like scenario we would not normally use trace level logging. See failure here https://github.com/NHSDigital/dtos-communication-management/actions/runs/11961025705/job/33347740004 which passed on the PR branch.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any …
> Lower function host logging levels

- compose.yml
- tests/end_to_end/test_file_upload_to_notifying_recipients.py
Check that the expected batch message data is recorded in the database when running end to end tests.
We have recently started recording batch message data in the database so verify this in end to end tests.
---
> Assert that batch message records are created in end to end tests

- infrastructure/tf-core/environments/integration.tfvars
- infrastructure/tf-core/environments/nft.tfvars
Just adding in the configuration to allow postgresql to run in both the nft and integration (int) environments.  They have both been run in these pipelines: - 
nft: - https://dev.azure.com/nhse-dtos/dtos-communication-management/_build/results?buildId=9039&view=results
int: - https://dev.azure.com/nhse-dtos/dtos-communication-management/_build/results?buildId=9040&view=results
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive …
> feat: Adding in postgresql config for nft and int

- compose.yml
- src/functions/message_status/function_app.py
- tests/end_to_end/Dockerfile
- tests/end_to_end/__init__.py
- tests/end_to_end/conftest.py
- tests/end_to_end/test_notify_callback_to_message_status_saved.py
- tests/integration/Dockerfile
- tests/integration/__init__.py
- tests/integration/test_message_status_recorder_saves_message_statuses.py
- tests/unit/message_status/test_function_app.py
Adds integration and end to end tests emulating how we receiving callbacks from NHS Notify and saving the request body to the database.
We have a function which is triggered by http requests from NHS Notify and receives a payload containing useful information about message delivery status.
---
> Add message status integration tests

- src/functions/notify/notifier.py
- src/shared/datastore.py
- tests/unit/shared/test_datastore.py
Remove env-level token caching. This won't work.
We know from Microsoft documentation that obtaining a MI credential token as we connect to the database is not advisable for production and that token caching is necessary. There's also anecdotal evidence of the token issuing endpoint failing to respond.
We tried to mitigate this by caching the token in the env, but this does not work well with a function app lifecycle.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove …
> Remove env token caching

- src/functions/process_pilot_data/pilot_bso_details.py
Use first 3 chars of filename to deduce BSO code. This is slightly more robust than splitting on whitespace.
---
> Take first 3 chars from filename regardless of whitespace

- src/functions/notify/function_app.py
- tests/unit/notify/test_function_app.py
- Restrict function http trigger method to POST
- Remove the dynamic portion of the function trigger path, we don't use it.
---
> Restrict Notify function http methods

- infrastructure/tf-core/key_vault.tf
- infrastructure/tf-core/postgresql.tf
- infrastructure/tf-core/storage.tf
This will prevent an issue encountered while building Production environment, where public access to a resource is removed before the VNet peering with the Hub has been established in both directions - confounding further attempts to run `terraform plan`. Effectively a situation could arise, depending on the resource creation order, in which the ADO Agent in the Managed DevOps Pool subnet becomes isolated from Azure resources which it has just created.
Prior to this fix, recovering from this scenario - via manual creation then `terraform import` of the VNet peering - was very difficult indeed given the private nature even of the Terraform state Storage Accounts.
Successfully deployed Production tf-core state: https://dev.azure.com/nhse-dtos/dtos-communication-management/_build/results?buil …
> fix: VNet peering manual dependency for private services

- .azuredevops/pipelines/acr-image-retag.yaml
- .azuredevops/pipelines/cd-infrastructure-dev-audit.yaml
- .azuredevops/pipelines/cd-infrastructure-dev-core.yaml
- .azuredevops/pipelines/cd-infrastructure-int-audit.yaml
- .azuredevops/pipelines/cd-infrastructure-int-core.yaml
- .azuredevops/pipelines/cd-infrastructure-nft-audit.yaml
- .azuredevops/pipelines/cd-infrastructure-nft-core.yaml
- .azuredevops/pipelines/cd-infrastructure-prd-audit.yaml
- .azuredevops/pipelines/cd-infrastructure-prd-core.yaml
- .azuredevops/pipelines/cd-infrastructure-pre-audit.yaml
- .azuredevops/pipelines/cd-infrastructure-pre-core.yaml
ACR image copying and re-tagging pipeline can now retag images in either Dev or Prod project ACRs, and migrate images between them. It preserves the PR and commit ref tags when migrating images.
One significant improvement here is the parallelism of the `az acr` jobs, which should result in a rapid pipeline execution, even for projects which have many Docker images. Furthermore there is no need for artifact storage nor multiple pipeline stages.
Linked to https://github.com/NHSDigital/dtos-devops-templates/pull/79
Example successful run:
https://dev.azure.com/nhse-dtos/dtos-communication-management/_build/results?buildId=10156&view=results
Previously, Docker image promotion into Prod environments was only possible via VM with Docker installed - by downloading, re-tagging, and uploading …
> fix: Enhance ACR copy/retag pipeline to publish to Preprod and Prod

- src/functions/message_status/function_app.py
Reverts NHSDigital/dtos-communication-management#115
We know HMAC verification works now.
> Revert "Log headers we use to verify requests"

- src/shared/uuid_generator.py
- tests/unit/shared/test_uuid_generator.py
Something that we spotted with test data is a blank field will cause an exception, this was down to bad test data but filter empty field values out when generating the recipient id.
---
> Make recipient id generator resilient to blank fields

- src/functions/notify/notifier.py
- tests/unit/notify/test_notifier.py
We don't want to halt all message sending if an exception occurs when sending the batch of messages. Log the error and continue.
---
> Log any exceptions when calling send_message

- src/functions/message_status/function_app.py
- tests/unit/message_status/test_function_app.py
Adds an http trigger for message status healthchecks. The healthcheck is as simple as possible for now.
This change won't have any effect in terms of monitoring until the relevant infrastructure PRs are merged and deployed.
---
> Add healthcheck endpoint to message status function

- tests/end_to_end/runner/test_csv_file_upload.py
Increase delay before database record assertions to 2 seconds.
1.5 seconds was marginal in allowing the blob trigger to execute, send a request to the NHS Notify API Stub and then save things to the database. 
---
> Increase delay to allow function app trigger time

- tests/end_to_end/nhs_notify_api_stub/app.py
Adds dynamic timestamps to NHS Notify API stub responses, you know for realism.
---
> Add dynamic timestamps to NHS Notify API stub server responses

- tests/end_to_end/nhs_notify_api_stub/Dockerfile
- tests/end_to_end/nhs_notify_api_stub/app.py
We serve a default happy-path response from the NHS Notify API stub server in our end to end tests, but this won't tell us if we start sending an invalid POST body. 
Add validation of the incoming post body, this will catch any changes which produce an invalid request.
We already have integration test coverage for invalid payloads but this ensures we don't have a false sense of security with the stubbed server.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR …
> Validate generated message batch post body on stub API

- src/notify/app/route_handlers/message.py
- src/notify/app/services/message_batch_dispatcher.py
- tests/integration/notify/app/route_handlers/test_message_batch.py
- tests/unit/notify/app/services/test_message_batch_dispatcher.py
This commit allows the incoming Authorization header value to be preserved and used in the request made to the NHS Notify API, otherwise the default credentials are used to generate the JWT / Bearer token. This fallback preserves existing BSO file upload functionality.
NHS Notify need to identify requests from clients to ensure the correct routing plans are in use.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We …
> Include the client bearer token if present in headers

- src/notify/app/route_handlers/message.py
- tests/end_to_end/runner/helpers.py
- tests/integration/notify/app/route_handlers/test_message_batch.py
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-8364
We now preserve the Authorization header from the client on message batch POST requests.
The OAuth2 authorization server will reject invalid or expired bearer tokens from the auth header.
We no longer need to verify the HMAC signature on this endpoint.
For the POST /message/batch endpoint only:
- Ensure the Authorization header value is of the correct format (ie `Bearer xyz`)
- Reject requests with no auth header
- Remove HMAC signature verification 
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other …
> Remove hmac verification on message batch endpoint

- src/notify/migrations/versions/37bae2d2c9ec_create_clients_table.py
- src/notify/migrations/versions/e9702592451c_add_client_id_to_message_batches.py
- Add `clients` database table with appropriate columns
- Add `message_batches.client_id` column and foreign key constraint, this is currently nullable as existing code does not populate this new column. Once this functionality is added we can add a NOT NULL constraint.
Consumers of the Communication Management API should be identified when making requests. 
Data should be identifiable and restricted per consumer or "client".
This needs to be modelled in the database and in code so that we associate batches of messages with the client who created them. 
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable …
> Add clients db migrations

- .github/workflows/cicd-1-pull-request.yaml
this container is currently erroring during CI
process as the name cannot be found. Pending a
more sustainable fix as per this chat [1] this
will allow PRs to go green for now.
[1] https://screening-discovery.slack.com/archives/C07QHFSV79U/p1752595562397039?thread_ts=1752584013.241669&cid=C07QHFSV79U
* Ignores the `nhs-notify-api` container for PR CI.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate …
> quick fix to ignore broken nhs-notify-api container for CI

- README.md
- src/notify/app/models.py
- src/notify/app/route_handlers/message.py
- src/notify/app/services/message_batch_dispatcher.py
- src/notify/app/services/message_batch_recorder.py
- src/notify/app/validators/request_validator.py
- src/notify/migrations/versions/891274ce0411_renaming_client_model_to_consumer.py
- tests/conftest.py
- tests/end_to_end/runner/helpers.py
- tests/end_to_end/runner/test_post_to_message_batch_endpoint.py
- tests/integration/notify/app/route_handlers/test_message_batch.py
- tests/unit/notify/app/services/test_message_batch_dispatcher.py
- tests/unit/notify/app/services/test_message_batch_recorder.py
- tests/unit/notify/app/services/test_status_reporter.py
- tests/unit/notify/app/validators/test_request_validator.py
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-9044
This is the first part of the process to introduce Consumer identification to MessageBatches - Introducing a required key in the headers to link an existing Consumer with a MessageBatch, and making the Consumer required in order to POST a MessageBatch. Part 2 of this ticket will introduce sending the Consumer key in headers when GETing Statuses.
In this PR we are:
* Assuming the consumer has awareness of a secret `consumer-key` to pass in the header, and we've pre-loaded the Consumer into our database
* Checking the Consumer exists in the `message_batch_dispatcher` and if it doesn't return 401
* If it does exist, then we add it as a fk onto the MessageBatch in our database 
Some more context on design decisions made here …
> DTOSS-9044: Require Consumer Key for MessageBatches

- compose.yml
Small `compose.yaml` fix to hopefully overcome a container build issue. Something I noticed when I first looked at the build scripts is that the scripts assume that container name and the service name will be identical - which they were not in this case. All the others are.
---
> fix: container build issue

- src/notify/app/route_handlers/message.py
- src/notify/app/route_handlers/status.py
- src/notify/app/validators/request_validator.py
- tests/end_to_end/runner/helpers.py
- tests/integration/notify/app/route_handlers/test_get_statuses_endpoint.py
- tests/integration/notify/app/route_handlers/test_message_batch.py
- tests/unit/notify/app/validators/test_request_validator.py
https://nhsd-jira.digital.nhs.uk/browse/DTOSS-10246
The GET and POST request header validation should be the same,[as set here](https://github.com/NHSDigital/dtos-communication-management/blob/main/src/notify/app/validators/request_validator.py#L55-L56) , on any endpoint called by a Consumer (see below), so that we can validate requests to the API. 
As noted on this PR https://github.com/NHSDigital/dtos-communication-management/pull/291#discussion_r2222319597 
We should expect an Authorization header for any request that is not GET /healthcheck or POST /status/create ie both POST /message/batch and GET /statuses.
So for requests coming from Consumers we would check:
Authorization header is present
API key header is present
API key matches
Consumer key header is present
Consumer key …
> DTOSS-10246: Consisten request headers for Consumer end points

- tests/unit/notify/app/commands/test_create_consumer.py
After pulling from main and running tests pytest stopped at the amended test.
Root cause was that db connections were left open by the `Session(database.engine())` calls.
We need to look into connection management in a future story and possibly think about a better pattern for managing db connections, ie pooling.
Weird this works fine on CI, perhaps the number of possible open connections is higher on the runner service?
Use `with Session(database.engine()) as session:` context manager in the unit test which was hanging up.
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-th …
> Use a context manager in test to ensure db connection is closed

- src/notify/app/commands/create_consumer.py
- tests/unit/notify/app/commands/test_create_consumer.py
- tests/unit/notify/app/queries/test_consumer.py
We create Consumers via a Flask admin command. We also cache consumers in `app.queries.consumer.fetch_all_cached` and use this function to check consumer tokens in requests to the API.
This PR:
Clears the list of consumers cached by `fetch_all_cached` when we invoke the `create-consumer` admin command.
---
> Clear cache when creating consumers
